mod 'puppet-nginx', '3.3.0'
mod 'puppetlabs-stdlib', '8.1.0'
mod 'puppetlabs-concat', '7.1.1'
mod 'puppetlabs-translate', '2.2.0'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '4.1.2'
